namespaced update

diff --git a/scripts/namespaced b/scripts/namespaced
--- a/scripts/namespaced
+++ b/scripts/namespaced
@@ -17,6 +17,10 @@ Options:
   -n --name <name>             Veth pair and network namespace name (default: nsd)
   -c --country <CODE>          Country code to compare if somehow you are still connected through VPN (e.g. VPN tethering)
   -d --dns <ip>                DNS servers in the namespace, use "," separator (default 1.1.1.1, 1.0.0.1)
+  -h --hosts-file <file>       /etc/hosts in the namespace
+  -p --program                 Program to launch in the namespace (graphical apps may require sudo -E)
+  -u --user                    User to launch --program, default is root, you may specify it as \$USER
+
   --veth0-ip <ip>              Veth0 ip address (default: 198.18.10.1)
   --veth1-ip <ip>              Veth0 ip address (default: 198.18.10.2)
   --fwmark <fwmark>            Fwmark of the routed packets (default: 105)
@@ -40,18 +44,19 @@ define_variables() {
   VETH0_IP="198.18.10.1"
   VETH1_IP="198.18.10.2"
   DNS="1.1.1.1, 1.0.0.1"
+  HOSTS_FILE=
+  PROGRAM=
+  PROGRAM_USER="root"
   FWMARK=105
   TABLE=105
   NOKILL=false
   NOCREATE=false
   
   NAMESPACE_GW=
-  DEFAULT_GW=
   DEFAULT_IFACE=
   NAMESERVER_1=
   NAMESERVER_2=
   OLD_IPV4_FORWARD=$(sysctl -n net.ipv4.ip_forward)
-  OLD_MASQUARADE=
 }
 
 parse_options() {
@@ -61,13 +66,16 @@ parse_options() {
       -n|--name) shift; NAME=$1; shift ;;
       -c|--country) shift; COUNTRY_CHECK=$1; shift ;;
       -d|--dns) shift; DNS=$1; shift ;;
+      -h|--hosts-file) shift; HOSTS_FILE=$1; shift ;;
+      -p|--program) shift; PROGRAM=$1; shift ;;
+      -u|--user) shift; PROGRAM_USER=$1; shift ;;
       --veth0-ip) shift; VETH0_IP=$1; shift ;;
       --veth1-ip) shift; VETH1_IP=$1; shift ;;
       --fwmark) shift; FWMARK=$1; shift ;;
       --table) shift; TABLE=$1; shift ;;
       --nokill) shift; NOKILL=true ;;
       --nocreate) shift; NOCREATE=true ;;
-      *) echo  "Invalid parameter: $1" 1>&2; exit 1 ;;
+      *) echo "Invalid parameter: $1" 1>&2; exit 1 ;;
     esac
   done
 
@@ -75,15 +83,15 @@ parse_options() {
     echo "This script must be run as root."
     exit 1
   fi
-  
-  if ip netns | grep -q "$NAME"; then
-    echo "This script is already running!"
-    exit 1
-  fi
 
   VETH0_NAME=$NAME"0"
   VETH1_NAME=$NAME"1"
   IFS=", " read -r NAMESERVER_1 NAMESERVER_2 <<< "$DNS"
+  
+  if ip link show | grep -q "$VETH0_NAME"; then
+    echo "This script is already running!"
+    exit 1
+  fi
 }
 
 ########################################################################################################################
@@ -92,64 +100,52 @@ get_gateway() {
   echo "Waiting for the default interface..."
   while true; do
     DEFAULT_IFACE=$(ip route show default | awk '{print $5; exit}')
-    DEFAULT_GW=$(ip route show default | awk '{print $9; exit}')
     NAMESPACE_GW=$(ip route show default | awk '{print $3; exit}')
-    if [[ -n "$DEFAULT_IFACE" && -n "$NAMESPACE_GW" && -n "$DEFAULT_GW" ]]; then
+    if [[ -n "$DEFAULT_IFACE" && -n "$NAMESPACE_GW" ]]; then
       break
     else
       sleep 3
     fi
   done
 
-  echo "Namespace gateway: $NAMESPACE_GW"
-  echo "Default gateway: $DEFAULT_GW"
-  echo "Default interface: $DEFAULT_IFACE"
-  OLD_MASQUARADE=$(iptables-save | grep -q -- "-A POSTROUTING -o $DEFAULT_IFACE -j MASQUERADE" && echo true || echo false)
+  echo -e "\nNamespace gateway: $NAMESPACE_GW"
+  echo -e "Default interface: $DEFAULT_IFACE\n"
 }
 
 do_rules() {
-  ip rule $1 fwmark $FWMARK table $TABLE 2> /dev/null
-  ip rule $1 from $VETH1_IP table $TABLE 2> /dev/null
-  ip rule $1 to $VETH1_IP table $TABLE 2> /dev/null
+  ip rule $1 fwmark $FWMARK table $TABLE
+  ip rule $1 from $VETH1_IP table $TABLE
+  ip rule $1 to $VETH1_IP table $TABLE
+  ip route $1 $VETH1_IP via $VETH0_IP dev $VETH0_NAME table $TABLE
+}
+
+do_route() {
   ip route $1 default via $NAMESPACE_GW dev $DEFAULT_IFACE table $TABLE 2> /dev/null
-  ip route $1 $VETH1_IP via $VETH0_IP dev $VETH0_NAME table $TABLE 2> /dev/null
 }
 
 do_iptables() {
-  iptables -t nat $1 POSTROUTING -o "$DEFAULT_IFACE" -j MASQUERADE
+  iptables $1 FORWARD -i $DEFAULT_IFACE -o $VETH0_NAME -j ACCEPT
+  iptables $1 FORWARD -o $DEFAULT_IFACE -i $VETH0_NAME -j ACCEPT
+  iptables $1 POSTROUTING -t nat -s $VETH1_IP/24 -o "$DEFAULT_IFACE" -j MASQUERADE
 }
 
-do_net_access() {
-  iptables $1 INPUT -i $VETH0_NAME -p icmp -d $NAMESERVER_1 -j ACCEPT 2> /dev/null
-  iptables $1 FORWARD -i $VETH0_NAME -p icmp -d $NAMESERVER_1 -j ACCEPT 2> /dev/null
-  iptables $1 OUTPUT -o $VETH0_NAME -p icmp -d $NAMESERVER_1 -j ACCEPT 2> /dev/null
-
-  iptables $1 INPUT -i $VETH0_NAME -p tcp --dport 80 -d 104.16.133.229 -j ACCEPT 2> /dev/null
-  iptables $1 FORWARD -i $VETH0_NAME -p tcp --dport 80 -d 104.16.133.229 -j ACCEPT 2> /dev/null
-  iptables $1 OUTPUT -o $VETH0_NAME -p tcp --sport 80 -d 104.16.133.229 -j ACCEPT 2> /dev/null
-  
-  iptables $1 INPUT -i $VETH0_NAME -j DROP 2> /dev/null
-  iptables $1 FORWARD -i $VETH0_NAME -j DROP 2> /dev/null
-  iptables $1 OUTPUT -o $VETH0_NAME -j DROP 2> /dev/null
+do_blackhole() {
+  iptables -t raw $1 PREROUTING -i $VETH0_NAME -p tcp -d 104.16.133.229 --dport 80 -j ACCEPT
+  iptables -t raw $1 PREROUTING -i $VETH0_NAME -p icmp -d $NAMESERVER_1 -j ACCEPT
+  iptables -t raw $1 PREROUTING -i $VETH0_NAME -d $VETH0_IP -j ACCEPT
+  iptables -t raw $1 PREROUTING -i $VETH0_NAME -d $VETH1_IP -j ACCEPT
+  iptables -t raw $1 PREROUTING -i $VETH0_NAME -j DROP
 }
 
 ########################################################################################################################
 
 conn_check() {
   (
-    local connected=true;
+    sleep 5
     while true; do
-      local masquarade=$(iptables-save | grep -q -- "-A POSTROUTING -o $DEFAULT_IFACE -j MASQUERADE" && echo true || echo false)
-
-      if [ "$masquarade" = false ]; then
-        echo "Iptables rules got deleted, restoring"
-        do_iptables "-A"
-      fi
-      if ! ip netns exec $NAME ping -c 1 -W 1 $NAMESERVER_1 &> /dev/null; then
-        connected=false
+      if ! ip netns exec $NAME ping -c 1 -W 3 $NAMESERVER_1 &> /dev/null; then
         echo "No ping from $NAMESERVER_1, restarting"
-        do_net_access "-D"
-        kill $RTMON_PID 2> /dev/null
+        kill $RTMON_PID &> /dev/null
         break
       fi
       sleep 10
@@ -158,14 +154,13 @@ conn_check() {
   CONN_CHECK_PID=$!
 }
 
-
 country_check() {
   (
-    local already_running=$(iptables-save | grep -q -- "-A INPUT -d $NAMESERVER_1/32 -i $VETH0_NAME -p icmp -j ACCEPT" && echo true || echo false)
+    local already_running=$(iptables-save | grep -q -- "-A PREROUTING -d 104.16.133.229/32 -i $VETH0_NAME -p tcp -m tcp --dport 80 -j ACCEPT" && echo true || echo false)
 
     if [[ -n "$COUNTRY_CHECK" && "$already_running" = false ]]; then
       echo "Checking country..."
-      do_net_access "-A"
+      do_blackhole "-A"
 
       while true; do
         local response=$(ip netns exec $NAME curl -m 3 -s http://104.16.133.229/cdn-cgi/trace)
@@ -179,7 +174,7 @@ country_check() {
             break
           else
             echo -e "IP: $ip\nCountry: $country"
-            do_net_access "-D"
+            do_blackhole "-D"
             break
           fi
         else
@@ -194,8 +189,9 @@ country_check() {
 
 rtmon() {
   (
+    local rtmon_pid=$BASHPID
     ip monitor route dev $DEFAULT_IFACE | while read -r line; do
-      [[ $line != *"$VETH0_IP"* && $line != *"$TABLE"* && $line != *"$NAME"* ]] && kill $BASHPID 2> /dev/null
+      [[ $line != *"$VETH0_IP"* && $line != *"$TABLE"* && $line != *"$NAME"* ]] && kill $rtmon_pid &> /dev/null
     done
   ) &
   RTMON_PID=$!
@@ -216,8 +212,9 @@ cleanup() {
     fi
 
     do_rules "del"
-    [ "$OLD_MASQUARADE" = false ] && do_iptables "-D"
-    do_net_access "-D"
+    do_route "del"
+    do_iptables "-D" &> /dev/null
+    do_blackhole "-D" &> /dev/null
     sysctl -wq net.ipv4.ip_forward=$OLD_IPV4_FORWARD &> /dev/null
 
     ip link del $VETH0_NAME &> /dev/null
@@ -235,7 +232,7 @@ init() {
   parse_options "$@"
   trap cleanup INT TERM
 
-  [ "$NOCREATE" = false] && ip netns add $NAME
+  [ "$NOCREATE" = false ] && ip netns add $NAME
   ip link add $VETH0_NAME type veth peer name $VETH1_NAME
   ip link set $VETH1_NAME netns $NAME
   ip addr add $VETH0_IP/24 dev $VETH0_NAME
@@ -244,24 +241,34 @@ init() {
   ip netns exec $NAME ip addr add $VETH1_IP/24 dev $VETH1_NAME
   ip netns exec $NAME ip link set $VETH1_NAME up
   ip netns exec $NAME ip route add default via $VETH0_IP
+  ip netns exec $NAME sysctl -wq net.ipv4.ping_group_range="$(sysctl -n net.ipv4.ping_group_range)"
+  do_rules "add"
+
   mkdir -p /etc/netns/$NAME
   echo -e "nameserver $NAMESERVER_1\nnameserver $NAMESERVER_2" > /etc/netns/$NAME/resolv.conf
+  [ -n "$HOSTS_FILE" ] && echo "Copying hosts file" && cp -v $HOSTS_FILE /etc/netns/$NAME/hosts && echo -e ""
   sysctl -wq net.ipv4.ip_forward=1
+
+  if [ -n "$PROGRAM" ]; then
+    echo "Launching program"
+    [ -z "$DBUS_SESSION_BUS_ADDRESS" ] && echo "\$Warning, \$DBUS_SESSION_BUS_ADDRESS is not available, please use sudo -E if you launch graphical apps"
+    ip netns exec $NAME sudo -E -u $PROGRAM_USER sh -c "$PROGRAM" 2>&1 | while IFS= read -r line; do echo "Program: $line"; done &
+  fi
 
   while true; do
     get_gateway
-    do_rules "add"
-    [ "$OLD_MASQUARADE" = false ] && do_iptables "-A"
+    do_route "add"
+    do_iptables "-A"
 
     rtmon 2> /dev/null
     country_check 2> /dev/null
     conn_check 2> /dev/null
     wait $RTMON_PID
-    kill $CONN_CHECK_PID $COUNTRY_CHECK_PID 2> /dev/null
+    kill $CONN_CHECK_PID $COUNTRY_CHECK_PID &> /dev/null
 
-    do_rules "del"
-    [ "$OLD_MASQUARADE" = false ] && do_iptables "-D"
-    do_net_access "-D"
+    do_route "del" &> /dev/null
+    do_blackhole "-D" &> /dev/null
+    do_iptables "-D" &> /dev/null
   done
 }
 
